apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj-cuda-balls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dj-cuda-balls
  template:
    metadata:
      labels:
        app: dj-cuda-balls
      annotations:
        nvidia.com/gpu: "1"
    spec:
      containers:
      - name: dj-cuda-balls
        image: dj-cuda:local
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        securityContext:
          privileged: true
      restartPolicy: Always
